version: '2.1'

# Run: docker-compose --project-name=ocean up

services:
  mongodb:
    image: mongo:3.6
    ports:
    - "27017:27017"
    command: mongod
    networks:
      backend:
        ipv4_address: 172.15.0.11

  parity-node:
    image: oceanprotocol/parity-ethereum:beta
    entrypoint: /opt/parity/parity
    command:
      --config /home/parity/parity/config/secretstoreclient.toml
      --db-path /home/parity/chains
      --keys-path /home/parity/.local/share/io.parity.ethereum/keys
      --base-path /home/parity/base
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
      --ws-interface all
      --jsonrpc-cors all
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-apis all
      --unsafe-expose
      --unlock 0x00bd138abd70e2f00903268f3db08f2d25677c9e
    volumes:
      - ./parity/parity/config:/home/parity/parity/config
      - parity-node:/home/parity/.local/share/io.parity.ethereum/
      - ./parity/parity/authorities/validator0.json:/home/parity/.local/share/io.parity.ethereum/keys/ocean-network/validator.json
      - ./parity/parity/keys:/home/parity/.local/share/io.parity.ethereum/keys/ocean-network
      - ./parity/parity/authorities/validator0.pwd:/home/parity/parity/validator.pwd
      - ./parity/parity/node0.network.key:/home/parity/.local/share/io.parity.ethereum/network/key
    ports:
      - 8545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.12

  secret-store:
    image: oceanprotocol/parity-ethereum:master
    # entrypoint: tail -f /dev/null
    entrypoint: /opt/parity/parity
    command:
      --config /etc/parity/secretstore/config.toml --jsonrpc-cors all --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-apis all
    volumes:
    - ./parity/secret_store/config/:/etc/parity/secretstore/
    - secret-store:/parity_data/
    - ./parity/secret_store/keys/:/parity_data/keys/ocean-network/
    ports:
    - 12000:12000
    - 12001:12001
    networks:
      backend:
        ipv4_address: 172.15.0.13

  keeper-contracts:
    image: oceanprotocol/keeper-contracts:${OCEAN_VERSION:-stable}
    networks:
      backend:
        ipv4_address: 172.15.0.14
    environment:
      LOCAL_CONTRACTS: "true"
      DEPLOY_CONTRACTS: ${DEPLOY_CONTRACTS}
      DATABASE_PATH: "/ganache-db"
      REUSE_DATABASE: ${REUSE_DATABASE}
      NETWORK_NAME: ${KEEPER_NETWORK_NAME}
      POA_HOST: "parity-node"
    volumes:
    - ${ARTIFACTS_FOLDER}:/keeper-contracts/artifacts/
    - ${GANACHE_DATABASE_PATH}/ganache-db:/ganache-db

  aquarius:
    image: oceanprotocol/aquarius:${OCEAN_VERSION:-stable}
    ports:
    - 5000:5000
    networks:
      backend:
        ipv4_address: 172.15.0.15
    depends_on:
    - keeper-contracts
    environment:
      KEEPER_HOST: http://parity-node
      DB_HOSTNAME: mongodb
      LOCAL_CONTRACTS: 'true'
    volumes:
    - ${ARTIFACTS_FOLDER}:/usr/local/keeper-contracts/:ro


networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.15.0.1/24
        gateway: 172.15.0.1

volumes:
  parity-node:
  secret-store:
