[parity]
chain = "/home/parity/config/chain.json"

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[account]
password = ["/home/parity/validator.pwd"]

[mining]
engine_signer = "0x00bd138abd70e2f00903268f3db08f2d25677c9e"
reseal_on_txs = "none"
force_sealing = true
reseal_min_period = 500

[network]
port = 30303
discovery = true
bootnodes = [
  "enode://65f9c708cd96fb4c1cfb80451ca8c304ca99660b92445b1da6323c5965332f37d4cf2c17d68ee9b413de6ce87c47c1e0a66e8d05ebe634e7ba559c67d0ec8853@172.15.0.12:30303",
  "enode://030ba626855043909feec09dfa03b9b186512156ea1dc6225801f014ba49b6b8ca1579287043da69645b8fb40a8685a05bcf35949b7363749bad89611eeebeea@172.15.0.13:30303",
  "enode://9495e2c34639ae6a8dbabfe7cb038d17be5e65879736b1fb56d0bfeaa01aa25f3802f45e774aae5ef7887bced5ed87a6490da75a1d894f6c7b09e6d6de62970d@172.15.0.18:30303"
]